# serverless.yml
 
# Service name
service:  aws-node-express-api
frameworkVersion: '3'

provider:
  name: aws
  runtimes: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
plugins:
  - serverless-offline
